ndcfg_tau: 35
dilate_tau: 35
inflate_tau: 0
dilate_settings: ./assets/dilate_settings/sd1.5_2048x2048.txt
ndcfg_dilate_settings: ./assets/ndcfg_dilate_settings/sd1.5_2048x2048.txt
disperse_settings: ./assets/disperse_settings/sd1.5_2048x2048.txt
disperse_transform: ./transforms/R20to1_new.mat
progressive: true
num_inference_steps: 50
inference_batch_size: 4
num_iters_per_prompt: 1
latent_height: 256
latent_width: 256