ndcfg_tau: 37
dilate_tau: 37
inflate_tau: 0
dilate_settings: ./assets/dilate_settings/sd2.1_2048x2048.txt
ndcfg_dilate_settings: ./assets/ndcfg_dilate_settings/sd2.1_2048x2048.txt
disperse_settings: ~
disperse_transform: ~
progressive: true
num_inference_steps: 50
inference_batch_size: 1
num_iters_per_prompt: 1
latent_height: 256
latent_width: 256