ndcfg_tau: 0
dilate_tau: 20
inflate_tau: 0
dilate_settings: ./assets/dilate_settings/sd2.1_1024x1024.txt
ndcfg_dilate_settings: ~
disperse_settings: ~
disperse_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 4
num_iters_per_prompt: 1
latent_height: 128
latent_width: 128