ndcfg_tau: 35
dilate_tau: 35
inflate_tau: 0
sdedit_tau: 0
dilate_settings: ./assets/dilate_settings/sdxl_4096x4096.txt
ndcfg_dilate_settings: ./assets/ndcfg_dilate_settings/sdxl_4096x4096.txt
disperse_settings: ~
disperse_transform: ~
progressive: true
num_inference_steps: 50
inference_batch_size: 1
num_iters_per_prompt: 1
latent_height: 512
latent_width: 512
pixel_height: 4096
pixel_width: 4096
