ndcfg_tau: 0
dilate_tau: 30
inflate_tau: 0
sdedit_tau: 0
dilate_settings: ./assets/dilate_settings/sdxl_2560x2560.txt
ndcfg_dilate_settings: ~
disperse_settings: ~
disperse_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 4
num_iters_per_prompt: 1
latent_height: 320
latent_width: 320
pixel_height: 2560
pixel_width: 2560
