name: Ruff Format

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/**"

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.2.2
      - name: Running format
        run: |
          ruff format --check .
